# Generated by Django 5.1.2 on 2025-01-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_contact_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
