# Generated by Django 5.1.3 on 2025-01-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipiemanagement',
            name='image2',
        ),
    ]
