# Generated by Django 5.1.3 on 2025-01-30 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0007_remove_recipiemanagement_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='userManagement.recipiemanagement'),
            preserve_default=False,
        ),
    ]
